import { createClient } from "https://esm.sh/@supabase/supabase-js@2.55.0";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const emailRx=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const text=(v:unknown)=>String(v??"").trim();
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS") return new Response("ok",{headers:cors});
 if(req.method!=="POST") return json({code:"METHOD_NOT_ALLOWED"},405);
 const url=Deno.env.get("SUPABASE_URL")||"", anon=Deno.env.get("SUPABASE_ANON_KEY")||"", service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
 const resend=Deno.env.get("RESEND_API_KEY")||"", from=Deno.env.get("WORKSPACE_NOTIFICATION_FROM_EMAIL")||"";
 const auth=req.headers.get("Authorization")||"";
 const caller=createClient(url,anon,{global:{headers:{Authorization:auth}}});
 const {data:{user}}=await caller.auth.getUser(); if(!user) return json({code:"AUTH_REQUIRED"},401);
 const body=await req.json().catch(()=>({})); const taskId=text(body.task_id), activityId=text(body.activity_id), cardUrl=text(body.card_url);
 if(!taskId||!activityId) return json({code:"INVALID_INPUT"},400);
 const admin=createClient(url,service,{auth:{persistSession:false}});
 const {data:task}=await admin.from("board_tasks").select("id,work_code,title,workspace_id,board_instance_id").eq("id",taskId).maybeSingle();
 if(!task?.workspace_id) return json({ok:true,sent:false,reason:"task_or_workspace_missing"});
 const {data:activity}=await admin.from("engineering_activity_log").select("id,note,actor_label,created_at").eq("id",activityId).eq("entity_id",taskId).maybeSingle();
 if(!activity) return json({ok:true,sent:false,reason:"progress_missing"});
 const key=`card-progress-email-v1:${activityId}`;
 const {data:existing}=await admin.from("engineering_activity_log").select("id,after_data").eq("action","card_progress_email_notification").contains("after_data",{idempotency_key:key}).limit(1);
 if(existing?.length) return json({ok:true,sent:existing[0].after_data?.state==="sent",reason:"already_processed"});
 const {data:setting}=await admin.from("board_workspace_notification_settings").select("progress_notification_enabled,progress_to_emails,progress_cc_emails,progress_bcc_emails").eq("workspace_id",task.workspace_id).maybeSingle();
 if(!setting?.progress_notification_enabled) return json({ok:true,sent:false,reason:"disabled"});
 const clean=(a:unknown)=>Array.from(new Set((Array.isArray(a)?a:[]).map(v=>text(v).toLowerCase()).filter(v=>emailRx.test(v))));
 const to=clean(setting.progress_to_emails), cc=clean(setting.progress_cc_emails).filter(v=>!to.includes(v)), bcc=clean(setting.progress_bcc_emails).filter(v=>!to.includes(v)&&!cc.includes(v));
 if(!to.length) return json({ok:true,sent:false,reason:"no_recipients"});
 if(!resend||!from) return json({code:"MAIL_CONFIG_MISSING"},503);
 const progress=text(activity.note); const code=text(task.work_code||task.id); const title=text(task.title);
 const subject=`${code} 有新的工作回報`;
 const message=[`工作：${code}「${title}」`,`回報人：${text(activity.actor_label)||"使用者"}`,`工作進度：${progress}`,cardUrl?`\n開啟此卡片：${cardUrl}`:""].filter(Boolean).join("\n");
 const auditBase={schema_version:"card-progress-email-v1",state:"pending",idempotency_key:key,task_id:taskId,activity_id:activityId,workspace_id:task.workspace_id,board_instance_id:task.board_instance_id||null};
 const {data:audit,error:auditErr}=await admin.from("engineering_activity_log").insert({entity_type:"board_task",entity_id:taskId,action:"card_progress_email_notification",after_data:auditBase,note:"Module C card progress Email notification",actor_id:user.id,actor_type:"system",actor_label:"System",activity_type:"system_activity"}).select("id").single();
 if(auditErr||!audit) return json({code:"AUDIT_CREATE_FAILED"},503);
 const resp=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resend}`,"Content-Type":"application/json"},body:JSON.stringify({from,to,cc,bcc,subject,text:message})});
 const provider=await resp.json().catch(()=>({})); const state=resp.ok?"sent":"provider_rejected";
 await admin.from("engineering_activity_log").update({after_data:{...auditBase,state,recipient_count:to.length,provider_request_id:text(provider?.id)||null,finalized_at:new Date().toISOString()}}).eq("id",audit.id);
 if(!resp.ok) return json({code:"MAIL_SEND_FAILED",audit_id:audit.id},502);
 return json({ok:true,sent:true,audit_id:audit.id,recipient_count:to.length});
});
