/*
 * Published C Mother Template identity.
 *
 * Generated by tools/template-publish.js. Do not edit manually; regenerate
 * after a PM-approved C template publication.
 */
(function (root, factory) {
  const api = factory(root);
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.ZhugeMotherTemplateRelease = api;
})(typeof window !== "undefined" ? window : globalThis, function (root) {
  "use strict";

  const RELEASE = Object.freeze({
  "schemaVersion": 1,
  "templateId": "c",
  "developmentVersion": "0.9.0-alpha.9.13",
  "developmentBuild": "20260901-1412",
  "publishedVersion": "0.9.0-alpha.9.13",
  "publishedBuild": "20260901-1412",
  "templateVersion": "0.9.0-alpha.9.13",
  "build": "20260901-1412",
  "sourceCommit": "d4fa8f9aafa4837cb87acc99f923cd91a53932c8",
  "sourceDirty": true,
  "sourceFingerprint": "11f2baa72ad0e9c71adbd7f6a6ca1bbbdbf9d391bed73903be3feb7d6797be94",
  "publishedAt": "2026-09-01T06:12:47.346Z",
  "consumers": {
    "c": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260901-1412",
      "status": "adopted"
    },
    "worktodo": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260901-1412",
      "status": "adopted"
    },
    "ai-board": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260901-1412",
      "status": "adopted"
    }
  }
});
  const CONSUMER_ALIASES = Object.freeze({
    c: "c",
    "c-mdtk": "c",
    c_mdtk: "c",
    template: "c",
    "template-c": "c",
    worktodo: "worktodo",
    "worktodo-new": "worktodo",
    "ai-board": "ai-board",
    ai_board: "ai-board",
    ai: "ai-board"
  });

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function currentProductIdentity() {
    const identity = root?.ZhugeFoundationConfig?.version || {};
    return { version: String(identity.version || ""), build: String(identity.build || "") };
  }

  function normalizeConsumer(value) {
    const key = String(value || "").trim().toLowerCase();
    return CONSUMER_ALIASES[key] || key || "unknown";
  }

  function forConsumer(value) {
    const consumerId = normalizeConsumer(value);
    const adoption = RELEASE.consumers[consumerId] || null;
    const identity = currentProductIdentity();
    const identityMatches = Boolean(adoption && identity.version === RELEASE.publishedVersion && identity.build === RELEASE.publishedBuild && adoption.templateVersion === RELEASE.publishedVersion && adoption.build === RELEASE.publishedBuild);
    return Object.freeze({
      ...clone(RELEASE),
      consumerId,
      adoption: adoption ? clone(adoption) : null,
      identityMatches,
      status: !adoption ? "unavailable" : identityMatches ? adoption.status : "stale"
    });
  }

  function applyToDocument(value, documentRef = root?.document) {
    const result = forConsumer(value);
    const body = documentRef?.body;
    if (!body) return result;
    body.dataset.templateId = RELEASE.templateId;
    body.dataset.templateConsumer = result.consumerId;
    body.dataset.templateVersion = result.publishedVersion;
    body.dataset.templateBuild = result.publishedBuild;
    body.dataset.templateAdoption = result.status;
    body.dataset.templateReleaseState = result.status;
    documentRef.querySelectorAll("[data-golden-master], [data-golden-master-surface], [data-c-operational-motherboard]").forEach(node => {
      node.dataset.templateId = RELEASE.templateId;
      node.dataset.templateConsumer = result.consumerId;
      node.dataset.templateVersion = result.publishedVersion;
      node.dataset.templateBuild = result.publishedBuild;
      node.dataset.templateAdoption = result.status;
    });
    return result;
  }

  function assertCurrent() {
    const errors = [];
    const identity = currentProductIdentity();
    if (identity.version !== RELEASE.publishedVersion) errors.push("product version does not match published template");
    if (identity.build !== RELEASE.publishedBuild) errors.push("product build does not match published template");
    ["c", "worktodo", "ai-board"].forEach(consumerId => {
      const adoption = RELEASE.consumers[consumerId];
      if (!adoption) errors.push(consumerId + " has no adoption record");
      else if (adoption.templateVersion !== RELEASE.publishedVersion || adoption.build !== RELEASE.publishedBuild) errors.push(consumerId + " adoption identity does not match published template");
    });
    return { ok: errors.length === 0, errors };
  }

  return Object.freeze({
    getSnapshot: () => clone(RELEASE),
    currentProductIdentity,
    normalizeConsumer,
    forConsumer,
    applyToDocument,
    assertCurrent
  });
});
