/*
 * Published C Mother Template identity.
 *
 * Generated by tools/template-publish.js. Do not edit manually; regenerate
 * after a PM-approved C template publication.
 */
(function (root, factory) {
  const api = factory(root);
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.ZhugeMotherTemplateRelease = api;
})(typeof window !== "undefined" ? window : globalThis, function (root) {
  "use strict";

  const RELEASE = Object.freeze({
  "schemaVersion": 1,
  "templateId": "c",
  "developmentVersion": "0.9.0-alpha.9.13",
  "developmentBuild": "20260926-0001",
  "publishedVersion": "0.9.0-alpha.9.13",
  "publishedBuild": "20260915-1707",
  "templateVersion": "0.9.0-alpha.9.13",
  "build": "20260915-1707",
  "developmentSourceCommit": "0c2a99bc004d3bd044b1b3795abbf6cde7c22f18",
  "developmentSourceFingerprint": "366e4dea53ab7105a92cf5d63b6f48f6a4bb8d9e3806cdf458e395d3316896cc",
  "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
  "sourceDirty": false,
  "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
  "publishedSnapshot": {
    "schemaVersion": 1,
    "version": "0.9.0-alpha.9.13",
    "build": "20260915-1707",
    "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
    "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
    "inventory": {
      "engineVersion": "c-mother-template-parity-v2",
      "baseline": "C Mother Template",
      "capabilities": [
        {
          "id": "feature-surface",
          "label": "功能",
          "fingerprint": "fnv1a-0473aa99",
          "present": true,
          "contract": {
            "owner": "C",
            "surface": "shared-board-runtime",
            "consumerBusinessRules": "adapter-only"
          },
          "machineContract": {
            "owner": "C",
            "surface": "shared-board-runtime",
            "consumerBusinessRules": "adapter-only"
          }
        },
        {
          "id": "ui-layout",
          "label": "UI／版面",
          "fingerprint": "fnv1a-8af77474",
          "present": true,
          "contract": {
            "surface": "golden-master",
            "markers": [
              "data-golden-master-surface",
              "data-golden-master-toolbar",
              "data-golden-master-board-mount",
              "data-shared-task-board"
            ]
          },
          "machineContract": {
            "surface": "golden-master",
            "markers": [
              "data-golden-master-surface",
              "data-golden-master-toolbar",
              "data-golden-master-board-mount",
              "data-shared-task-board"
            ]
          }
        },
        {
          "id": "shared-components",
          "label": "共用元件",
          "fingerprint": "fnv1a-93253ecb",
          "present": true,
          "contract": {
            "goldenMaster": [
              "renderHeader",
              "renderHeaderActions",
              "renderToolbar",
              "renderOperations",
              "mountOperations",
              "renderCard",
              "renderColumns",
              "renderBoard",
              "renderDrawer",
              "render",
              "mount",
              "bindBoard"
            ],
            "board": [
              "CARD_DRAG_TYPE",
              "COLUMN_DRAG_TYPE",
              "renderColumns",
              "render",
              "bind"
            ],
            "card": [
              "render"
            ],
            "drawer": [
              "renderProperties",
              "render",
              "mount"
            ]
          },
          "machineContract": {
            "goldenMaster": [
              "renderHeader",
              "renderHeaderActions",
              "renderToolbar",
              "renderOperations",
              "mountOperations",
              "renderCard",
              "renderColumns",
              "renderBoard",
              "renderDrawer",
              "render",
              "mount",
              "bindBoard"
            ],
            "board": [
              "CARD_DRAG_TYPE",
              "COLUMN_DRAG_TYPE",
              "renderColumns",
              "render",
              "bind"
            ],
            "card": [
              "render"
            ],
            "drawer": [
              "renderProperties",
              "render",
              "mount"
            ]
          }
        },
        {
          "id": "card",
          "label": "Card",
          "fingerprint": "fnv1a-485684a2",
          "present": true,
          "contract": {
            "renderer": "ZhugeSharedTaskCard.render",
            "framework": "shared-task-card"
          },
          "machineContract": {
            "renderer": "ZhugeSharedTaskCard.render",
            "framework": "shared-task-card"
          }
        },
        {
          "id": "drawer",
          "label": "Drawer",
          "fingerprint": "fnv1a-77b546ca",
          "present": true,
          "contract": {
            "renderer": "ZhugeSharedTaskDrawer.render",
            "framework": "shared-task-drawer",
            "regions": [
              "header",
              "work-body",
              "activity"
            ],
            "agreementScheduleFrame": {
              "key": "agreement-schedule",
              "framework": "shared-task-drawer-property",
              "label": "約定日期／約定期間",
              "editor": "controlled-shared-agreement-date-editor",
              "dataIndependent": true
            }
          },
          "machineContract": {
            "renderer": "ZhugeSharedTaskDrawer.render",
            "framework": "shared-task-drawer",
            "regions": [
              "header",
              "work-body",
              "activity"
            ],
            "agreementScheduleFrame": {
              "key": "agreement-schedule",
              "framework": "shared-task-drawer-property",
              "label": "約定日期／約定期間",
              "editor": "controlled-shared-agreement-date-editor",
              "dataIndependent": true
            }
          }
        },
        {
          "id": "checklist",
          "label": "Checklist",
          "fingerprint": "fnv1a-17dced0b",
          "present": true,
          "contract": {
            "formalGate": "pm-acceptance",
            "engineeringEvidence": [
              "developer-qa",
              "gpt-review",
              "regression-evidence"
            ],
            "runtimeGate": "completionGateStatus"
          },
          "machineContract": {
            "formalGate": "pm-acceptance",
            "engineeringEvidence": [
              "developer-qa",
              "gpt-review",
              "regression-evidence"
            ],
            "runtimeGate": "completionGateStatus"
          }
        },
        {
          "id": "attachment",
          "label": "Attachment",
          "fingerprint": "fnv1a-3e54d8fd",
          "present": true,
          "contract": {
            "scopes": [
              "task",
              "progress_note"
            ],
            "actions": [
              "addGeneralAttachment",
              "addProgressAttachment",
              "deleteAttachment"
            ]
          },
          "machineContract": {
            "scopes": [
              "task",
              "progress_note"
            ],
            "actions": [
              "addGeneralAttachment",
              "addProgressAttachment",
              "deleteAttachment"
            ]
          }
        },
        {
          "id": "progress",
          "label": "Progress",
          "fingerprint": "fnv1a-c448ef61",
          "present": true,
          "contract": {
            "timeline": "shared-task-timeline",
            "source": "engineering_activity_log",
            "classifier": "ZhugeSharedActivityClassifier"
          },
          "machineContract": {
            "timeline": "shared-task-timeline",
            "source": "engineering_activity_log",
            "classifier": "ZhugeSharedActivityClassifier"
          }
        },
        {
          "id": "drag-drop",
          "label": "Drag & Drop",
          "fingerprint": "fnv1a-b76ffef2",
          "present": true,
          "contract": {
            "cardType": "application/x-zhuge-shared-task-card",
            "columnType": "application/x-zhuge-shared-task-column",
            "handler": "ZhugeSharedTaskBoard.bind"
          },
          "machineContract": {
            "cardType": "application/x-zhuge-shared-task-card",
            "columnType": "application/x-zhuge-shared-task-column",
            "handler": "ZhugeSharedTaskBoard.bind"
          }
        },
        {
          "id": "shared-action-entry",
          "label": "共用操作入口",
          "fingerprint": "fnv1a-6d17f5ed",
          "present": true,
          "contract": {
            "contract": "ZhugeSharedTaskActionContract",
            "adapters": "ZhugeSharedTaskActionAdapters",
            "singleRuntime": true
          },
          "machineContract": {
            "contract": "ZhugeSharedTaskActionContract",
            "adapters": "ZhugeSharedTaskActionAdapters",
            "singleRuntime": true
          }
        },
        {
          "id": "operation-method",
          "label": "操作方式",
          "fingerprint": "fnv1a-4b2f0722",
          "present": true,
          "contract": {
            "actions": [
              "addChecklist",
              "addGeneralAttachment",
              "addProgressAttachment",
              "addProgressNote",
              "confirm",
              "createTask",
              "createWorkspace",
              "deleteAttachment",
              "deleteChecklist",
              "deleteProgressNote",
              "deleteTask",
              "deleteWorkspace",
              "editProgressNote",
              "moveWorkspace",
              "renameWorkspace",
              "reorderWorkspace",
              "setAgreementSchedule",
              "updateAttachmentMetadata",
              "updateChecklist",
              "updateContent",
              "updateGovernanceChecklist",
              "updateTitle"
            ],
            "readBack": "consumer-adapter",
            "duplicateConsumerRenderer": false
          },
          "machineContract": {
            "actions": [
              "addChecklist",
              "addGeneralAttachment",
              "addProgressAttachment",
              "addProgressNote",
              "confirm",
              "createTask",
              "createWorkspace",
              "deleteAttachment",
              "deleteChecklist",
              "deleteProgressNote",
              "deleteTask",
              "deleteWorkspace",
              "editProgressNote",
              "moveWorkspace",
              "renameWorkspace",
              "reorderWorkspace",
              "setAgreementSchedule",
              "updateAttachmentMetadata",
              "updateChecklist",
              "updateContent",
              "updateGovernanceChecklist",
              "updateTitle"
            ],
            "readBack": "consumer-adapter",
            "duplicateConsumerRenderer": false
          }
        },
        {
          "id": "lifecycle-flow",
          "label": "操作流程",
          "fingerprint": "fnv1a-7ab13688",
          "present": true,
          "contract": {
            "flow": [
              "read",
              "render",
              "shared-action",
              "cloud-read-back"
            ],
            "pmCompletion": "formal-pm-acceptance",
            "dragAndDrawer": "same-contract"
          },
          "machineContract": {
            "flow": [
              "read",
              "render",
              "shared-action",
              "cloud-read-back"
            ],
            "pmCompletion": "formal-pm-acceptance",
            "dragAndDrawer": "same-contract"
          }
        },
        {
          "id": "runtime-behavior",
          "label": "Runtime Behavior",
          "fingerprint": "fnv1a-e4033fcd",
          "present": true,
          "contract": {
            "runtime": "ZhugeBoardRuntime",
            "methods": [
              "refresh",
              "openTaskDetail",
              "moveTaskToWorkspace",
              "completionGateStatus",
              "completionGateMessage",
              "runParityGuard"
            ],
            "behavior": "shared-canonical"
          },
          "machineContract": {
            "runtime": "ZhugeBoardRuntime",
            "methods": [
              "refresh",
              "openTaskDetail",
              "moveTaskToWorkspace",
              "completionGateStatus",
              "completionGateMessage",
              "runParityGuard"
            ],
            "behavior": "shared-canonical"
          }
        },
        {
          "id": "publish-adopt-boundary",
          "label": "Publish／Adopt 邊界",
          "fingerprint": "fnv1a-8d5d8bb8",
          "present": true,
          "contract": {
            "publish": "update",
            "adopt": "update",
            "parity": "compare-detect-report-only",
            "parityDoesNotRepair": true
          },
          "machineContract": {
            "publish": "update",
            "adopt": "update",
            "parity": "compare-detect-report-only",
            "parityDoesNotRepair": true
          }
        },
        {
          "id": "data-boundary",
          "label": "資料邊界",
          "fingerprint": "fnv1a-02a42424",
          "present": true,
          "contract": {
            "baseline": "C",
            "compareDirection": "consumer-to-c",
            "ignored": [
              "data",
              "workspace",
              "card-content",
              "identity"
            ]
          },
          "machineContract": {
            "baseline": "C",
            "compareDirection": "consumer-to-c",
            "ignored": [
              "data",
              "workspace",
              "card-content",
              "identity"
            ]
          }
        }
      ]
    },
    "behaviorContract": {
      "id": "module-c-lifecycle-acceptance-v2",
      "family": "module-c-lifecycle-acceptance",
      "source": "module-c-mother",
      "workspaceDecision": "canonical",
      "completionDecision": "canonical",
      "reopenDecision": "canonical",
      "acceptance": "canonical",
      "audit": "canonical",
      "atomicity": "single-transaction",
      "workflowOwner": "board-instance",
      "workflowVersioning": "draft-published-retired-immutable",
      "currentStepBinding": "board_tasks.workflow_version_id+current_workflow_step_id",
      "workflowResolution": "cloud-definition",
      "runtimeInference": "forbidden"
    }
  },
  "publishedAt": "2026-09-15T14:49:07.294293+00:00",
  "consumers": {
    "c": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260915-1707",
      "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
      "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
      "status": "adopted",
      "adoptedAt": "2026-09-15T14:49:07.481175+00:00",
      "adoptedBy": "ac5afcc7-f045-41a9-8827-eaf085a04c0d",
      "publishedAt": "2026-09-15T14:49:07.294293+00:00",
      "cloudConsumerId": "c"
    },
    "worktodo": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260915-1707",
      "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
      "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
      "status": "published_pending_reload",
      "publishedAt": "2026-09-15T14:49:07.294293+00:00",
      "cloudConsumerId": "worktodo"
    },
    "ai-board": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260915-1707",
      "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
      "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
      "status": "published_pending_reload",
      "publishedAt": "2026-09-15T14:49:07.294293+00:00",
      "cloudConsumerId": "ai-board"
    },
    "investment-ivtk": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260915-1707",
      "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
      "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
      "status": "adopted",
      "adoptedAt": "2026-09-15T14:49:27.402955+00:00",
      "adoptedBy": "ac5afcc7-f045-41a9-8827-eaf085a04c0d",
      "publishedAt": "2026-09-15T14:49:07.294293+00:00",
      "cloudConsumerId": "81f49fc7-ac0f-428e-8fcd-5ee612c52993"
    },
    "worklog-procurement": {
      "templateVersion": "0.9.0-alpha.9.13",
      "build": "20260915-1707",
      "sourceCommit": "d792b4b871450c87926c764ede7c1be8ce3684ec",
      "sourceFingerprint": "0b0aee84d739cb2790aac5ea37820fb1e198c9c4086518f9d2110aec8f2d6516",
      "status": "published_pending_reload",
      "publishedAt": "2026-09-15T14:49:07.294293+00:00",
      "cloudConsumerId": "38d8d4b1-6d01-4d58-835b-b2beb61fc6b9"
    }
  }
});
  const CONSUMER_ALIASES = Object.freeze({
    c: "c",
    "c-mdtk": "c",
    c_mdtk: "c",
    template: "c",
    "template-c": "c",
    worktodo: "worktodo",
    "worktodo-new": "worktodo",
    "ai-board": "ai-board",
    ai_board: "ai-board",
    ai: "ai-board"
  });

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function currentProductIdentity() {
    const identity = root?.ZhugeFoundationConfig?.version || {};
    return {
      version: String(identity.version || ""),
      build: String(identity.build || ""),
      sourceCommit: String(identity.sourceCommit || RELEASE.developmentSourceCommit || ""),
      sourceFingerprint: String(identity.sourceFingerprint || RELEASE.developmentSourceFingerprint || "")
    };
  }

  function normalizeConsumer(value) {
    const key = String(value || "").trim().toLowerCase();
    return CONSUMER_ALIASES[key] || key || "unknown";
  }

  function forConsumer(value) {
    const consumerId = normalizeConsumer(value);
    const adoption = RELEASE.consumers[consumerId] || null;
    const identity = currentProductIdentity();
    const sourceIdentityMatches = Boolean(
      identity.sourceCommit
      && identity.sourceFingerprint
      && RELEASE.sourceCommit
      && RELEASE.sourceFingerprint
      && identity.sourceCommit === RELEASE.sourceCommit
      && identity.sourceFingerprint === RELEASE.sourceFingerprint
    );
    const identityMatches = Boolean(adoption && identity.version === RELEASE.publishedVersion && identity.build === RELEASE.publishedBuild && adoption.templateVersion === RELEASE.publishedVersion && adoption.build === RELEASE.publishedBuild && sourceIdentityMatches);
    return Object.freeze({
      ...clone(RELEASE),
      consumerId,
      adoption: adoption ? clone(adoption) : null,
      identityMatches,
      status: !adoption ? "unavailable" : identityMatches ? adoption.status : "stale"
    });
  }

  function applyToDocument(value, documentRef = root?.document) {
    const result = forConsumer(value);
    const body = documentRef?.body;
    if (!body) return result;
    body.dataset.templateId = RELEASE.templateId;
    body.dataset.templateConsumer = result.consumerId;
    body.dataset.templateVersion = result.publishedVersion;
    body.dataset.templateBuild = result.publishedBuild;
    body.dataset.templateAdoption = result.status;
    body.dataset.templateReleaseState = result.status;
    documentRef.querySelectorAll("[data-golden-master], [data-golden-master-surface], [data-c-operational-motherboard]").forEach(node => {
      node.dataset.templateId = RELEASE.templateId;
      node.dataset.templateConsumer = result.consumerId;
      node.dataset.templateVersion = result.publishedVersion;
      node.dataset.templateBuild = result.publishedBuild;
      node.dataset.templateAdoption = result.status;
    });
    return result;
  }

  function assertCurrent() {
    const errors = [];
    const identity = currentProductIdentity();
    if (identity.version !== RELEASE.publishedVersion) errors.push("product version does not match published template");
    if (identity.build !== RELEASE.publishedBuild) errors.push("product build does not match published template");
    ["c", "worktodo", "ai-board", "investment-ivtk"].forEach(consumerId => {
      const adoption = RELEASE.consumers[consumerId];
      if (!adoption) errors.push(consumerId + " has no adoption record");
      else if (adoption.templateVersion !== RELEASE.publishedVersion || adoption.build !== RELEASE.publishedBuild) errors.push(consumerId + " adoption identity does not match published template");
    });
    return { ok: errors.length === 0, errors };
  }

  return Object.freeze({
    getSnapshot: () => clone(RELEASE),
    currentProductIdentity,
    normalizeConsumer,
    forConsumer,
    applyToDocument,
    assertCurrent
  });
});
