#!/usr/bin/env node
/*
 * C Mother Template publish / adoption identity gate.
 *
 * The tool only creates and verifies a release record. It does not modify
 * Cloud, data, runtime behavior, or consumer domain contracts.
 */
"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

const ROOT = path.join(__dirname, "..");
const RELEASE_FILE = path.join(ROOT, "shared", "config", "template-release.js");
const VERSION_FILE = path.join(ROOT, "version.json");
const HTML_FILES = [
  "app/Board/template-preview/index.html",
  "app/Board/worktodo/index.html",
  "app/Board/ai/index.html",
  "modules/worklog/index.html"
];
const CANONICAL_TEMPLATE_FILES = [
  "shared/components/golden-master-runtime.js",
  "shared/components/golden-master.js",
  "shared/components/task-board.js",
  "shared/components/task-card.js",
  "shared/components/task-drawer.js",
  "shared/components/task-action-contract.js",
  "shared/components/task-action-adapters.js",
  "shared/board/board-read-service.js",
  "shared/components/activity-classifier.js",
  "shared/components/activity-text-renderer.js",
  "shared/components/task-card-summary.js",
  "shared/components/c-template-preview.js",
  "shared/services/template-release-service.js",
  "shared/config/version.js"
];

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), "utf8");
}

function git(args) {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim();
}

function sourceFingerprint() {
  const hash = crypto.createHash("sha256");
  CANONICAL_TEMPLATE_FILES.forEach(file => {
    hash.update(file);
    hash.update("\0");
    hash.update(read(file));
    hash.update("\0");
  });
  return hash.digest("hex");
}

function rootIdentity() {
  const version = JSON.parse(read("version.json"));
  return {
    version: String(version.version || ""),
    build: String(version.build || "")
  };
}

function renderModule(record) {
  return `/*\n * Published C Mother Template identity.\n *\n * Generated by tools/template-publish.js. Do not edit manually; regenerate\n * after a PM-approved C template publication.\n */\n(function (root, factory) {\n  const api = factory(root);\n  if (typeof module === "object" && module.exports) module.exports = api;\n  if (root) root.ZhugeMotherTemplateRelease = api;\n})(typeof window !== "undefined" ? window : globalThis, function (root) {\n  "use strict";\n\n  const RELEASE = Object.freeze(${JSON.stringify(record, null, 2)});\n  const CONSUMER_ALIASES = Object.freeze({\n    c: "c",\n    "c-mdtk": "c",\n    c_mdtk: "c",\n    template: "c",\n    "template-c": "c",\n    worktodo: "worktodo",\n    "worktodo-new": "worktodo",\n    "ai-board": "ai-board",\n    ai_board: "ai-board",\n    ai: "ai-board"\n  });\n\n  function clone(value) {\n    return JSON.parse(JSON.stringify(value));\n  }\n\n  function currentProductIdentity() {\n    const identity = root?.ZhugeFoundationConfig?.version || {};\n    return { version: String(identity.version || ""), build: String(identity.build || "") };\n  }\n\n  function normalizeConsumer(value) {\n    const key = String(value || "").trim().toLowerCase();\n    return CONSUMER_ALIASES[key] || key || "unknown";\n  }\n\n  function forConsumer(value) {\n    const consumerId = normalizeConsumer(value);\n    const adoption = RELEASE.consumers[consumerId] || null;\n    const identity = currentProductIdentity();\n    const identityMatches = Boolean(adoption && identity.version === RELEASE.publishedVersion && identity.build === RELEASE.publishedBuild && adoption.templateVersion === RELEASE.publishedVersion && adoption.build === RELEASE.publishedBuild);\n    return Object.freeze({\n      ...clone(RELEASE),\n      consumerId,\n      adoption: adoption ? clone(adoption) : null,\n      identityMatches,\n      status: !adoption ? "unavailable" : identityMatches ? adoption.status : "stale"\n    });\n  }\n\n  function applyToDocument(value, documentRef = root?.document) {\n    const result = forConsumer(value);\n    const body = documentRef?.body;\n    if (!body) return result;\n    body.dataset.templateId = RELEASE.templateId;\n    body.dataset.templateConsumer = result.consumerId;\n    body.dataset.templateVersion = result.publishedVersion;\n    body.dataset.templateBuild = result.publishedBuild;\n    body.dataset.templateAdoption = result.status;\n    body.dataset.templateReleaseState = result.status;\n    documentRef.querySelectorAll("[data-golden-master], [data-golden-master-surface], [data-c-operational-motherboard]").forEach(node => {\n      node.dataset.templateId = RELEASE.templateId;\n      node.dataset.templateConsumer = result.consumerId;\n      node.dataset.templateVersion = result.publishedVersion;\n      node.dataset.templateBuild = result.publishedBuild;\n      node.dataset.templateAdoption = result.status;\n    });\n    return result;\n  }\n\n  function assertCurrent() {\n    const errors = [];\n    const identity = currentProductIdentity();\n    if (identity.version !== RELEASE.publishedVersion) errors.push("product version does not match published template");\n    if (identity.build !== RELEASE.publishedBuild) errors.push("product build does not match published template");\n    ["c", "worktodo", "ai-board"].forEach(consumerId => {\n      const adoption = RELEASE.consumers[consumerId];\n      if (!adoption) errors.push(consumerId + " has no adoption record");\n      else if (adoption.templateVersion !== RELEASE.publishedVersion || adoption.build !== RELEASE.publishedBuild) errors.push(consumerId + " adoption identity does not match published template");\n    });\n    return { ok: errors.length === 0, errors };\n  }\n\n  return Object.freeze({\n    getSnapshot: () => clone(RELEASE),\n    currentProductIdentity,\n    normalizeConsumer,\n    forConsumer,\n    applyToDocument,\n    assertCurrent\n  });\n});\n`;
}

function createRecord() {
  const identity = rootIdentity();
  const commit = git(["rev-parse", "HEAD"]);
  const dirty = Boolean(git(["status", "--porcelain"]));
  const adoption = consumer => ({ templateVersion: identity.version, build: identity.build, status: "adopted" });
  return {
    schemaVersion: 1,
    templateId: "c",
    developmentVersion: identity.version,
    developmentBuild: identity.build,
    publishedVersion: identity.version,
    publishedBuild: identity.build,
    templateVersion: identity.version,
    build: identity.build,
    sourceCommit: commit,
    sourceDirty: dirty,
    sourceFingerprint: sourceFingerprint(),
    publishedAt: new Date().toISOString(),
    consumers: {
      c: adoption("c"),
      worktodo: adoption("worktodo"),
      "ai-board": adoption("ai-board")
    }
  };
}

function loadRecord() {
  delete require.cache[require.resolve(RELEASE_FILE)];
  return require(RELEASE_FILE).getSnapshot();
}

function check() {
  const errors = [];
  const record = loadRecord();
  const identity = rootIdentity();
  const expect = (condition, message) => { if (!condition) errors.push(message); };
  expect(record.schemaVersion === 1, "release schemaVersion must be 1");
  expect(record.templateId === "c", "templateId must be c");
  ["version", "build"].forEach(key => {
    expect(record[`published${key[0].toUpperCase()}${key.slice(1)}`] === identity[key], `published ${key} must match version.json`);
    expect(record[`development${key[0].toUpperCase()}${key.slice(1)}`] === identity[key], `development ${key} must match version.json`);
  });
  expect(record.templateVersion === record.publishedVersion, "templateVersion must match publishedVersion");
  expect(record.build === record.publishedBuild, "build must match publishedBuild");
  expect(record.sourceCommit && record.sourceCommit !== "PENDING_GENERATION", "sourceCommit must be generated");
  expect(record.sourceFingerprint && record.sourceFingerprint === sourceFingerprint(), "sourceFingerprint must match canonical source");
  ["c", "worktodo", "ai-board"].forEach(consumer => {
    const adoption = record.consumers?.[consumer];
    expect(adoption, `${consumer} adoption record is missing`);
    if (adoption) {
      expect(adoption.templateVersion === record.publishedVersion, `${consumer} templateVersion mismatch`);
      expect(adoption.build === record.publishedBuild, `${consumer} build mismatch`);
      expect(adoption.status === "adopted", `${consumer} is not marked adopted`);
    }
  });
  HTML_FILES.forEach(file => {
    const html = read(file);
    expect(html.includes(`shared/config/template-release.js?v=${record.publishedBuild}`), `${file} missing matching template-release cache-buster`);
  });
  if (errors.length) {
    console.error(["Template publish check: FAIL", ...errors.map(error => `- ${error}`)].join("\n"));
    return false;
  }
  console.log(`Template publish check: PASS (${record.publishedVersion} / ${record.publishedBuild})`);
  return true;
}

const mode = process.argv[2] || "--check";
if (mode === "--write") {
  fs.writeFileSync(RELEASE_FILE, renderModule(createRecord()), "utf8");
  console.log(`Published C template metadata written: ${path.relative(ROOT, RELEASE_FILE)}`);
} else if (mode === "--check") {
  process.exitCode = check() ? 0 : 1;
} else {
  console.error("Usage: node tools/template-publish.js --write|--check");
  process.exitCode = 2;
}
